Allow RC and milestone releases
ADTRAN/gradle-scala-multiversion-plugin pull request #15
Opened 2018-11-07 02:52 UTC by SimY4

Allow to specify milestone and release candidate versions of scala standard library and compiler.

2018-11-07 15:01 UTC, kbielefe reviewed
:+1:  Would it make sense to consider making the `RC` and `M` case insensitive?

2018-11-07 17:16 UTC, nathanalderson requested changes
Great changes!

One request inline. Also, you need to include a commit whose comment begins with either `feat:` for new feature or `fix:` for a fix (I think this PR could be considered either). This will make the semantic versioning tool bump the version number correctly. The easiest thing would be to just make sure your next commit includes `fix:`. You could also rewrite the first commit message (:see_no_evil:) or add an empty commit if you feel like it. I'm not picky.

2018-11-07 17:16 UTC, nathanalderson commented on src/test/groovy/unit/TestScalaMultiVersionPlugin.groovy
> +    void testMavenPomMilestoneRelease() {
Can we integrate this test with the previous one?

```scala
void testMavenPom() {
    ["2.12.1", "2.13.0-M5"].each {
        ...
    }
}
```

2018-11-07 21:51 UTC, SimY4 commented
@kbielefe if I may, I would suggest making this regex configurable by the end user with a reasonable default (say, standard Major.Minor.Patch regex). Just so if scala community decide to follow a different versioning style, code-change will not be necessary.

2018-11-07 22:09 UTC, nathanalderson approved these changes

2018-11-07 22:37 UTC, nathanalderson commented
Configurable is always nice. The convention for now seems to be capital letters though, and the maven resolution seems to be case-sensitive, so I think the current regex is fine as is or as a default if you want to make it configurable.

2018-11-07 23:44 UTC, SimY4 commented
@nathanalderson I can raise another PR to make it configurable.

Thanks

2018-11-19 05:56 UTC, SimY4 commented
Is there something else I should do to move forward with these changes?

2018-11-19 17:08 UTC, nathanalderson commented
Sorry! I must have missed your previous comment about raising another PR. That works for me. Thanks for contributing!

2018-11-19 17:08 UTC, merged